//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsuranceQuote
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote
    {
        public int Id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<short> car_year { get; set; }
        public Nullable<int> car_make { get; set; }
        public string car_model { get; set; }
        public Nullable<bool> had_dui { get; set; }
        public Nullable<short> sp_ticket { get; set; }
        public string coverage { get; set; }
        public Nullable<int> premium { get; set; }
    }
}
